repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive]

  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate Conventional Commit Message
        entry: python scripts/validate_commit_msg.py
        language: system
        stages: [commit-msg]
