repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: validate-commit-msg
        name: Validate Conventional Commit Message
        entry: .venv/bin/python scripts/validate_commit_msg.py
        language: system
        stages: [commit-msg]
